version: 2
formats: all
python:
  version: 3.7
  system_packages: true
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
      extra_requirements:
        - docs

